# Generated by Django 4.1.1 on 2022-09-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("birth_date", models.DateField()),
                ("address", models.CharField(max_length=80)),
                ("phone", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=50)),
                ("emp_id", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
